### ISSUE TITLE
SQL sintax error

### ISSUE THREAD

**Issue by ViniciusFillos** [NathanPatrzyk/triggers-sql#1]
a partir do primeiro insert da tabela produtos, os 'values' se repetem 2x

**Comment by ViniciusFillos** [comment]
problema resolvido

**Comment by NathanPatrzyk** [comment]
Ops, que bom que deu boa, devo ter colado duas vezes sem querer, como tava executando linha a linha, não vi o erro. Imagino que deu um trabalhinho para achar o erro, foi mal. Aí amanhã já termino de montar os slides.
